# Generated by Django 4.2.13 on 2024-07-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_code',
            field=models.PositiveIntegerField(default=409285),
        ),
    ]
