# Generated by Django 4.2.13 on 2024-09-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodels', '0002_alter_customuser_activate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_code',
            field=models.PositiveIntegerField(default=151728),
        ),
    ]
