# Generated by Django 4.2.13 on 2024-06-27 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=50)),
                ('subjectImage', models.ImageField(upload_to='subectimages')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseImage', models.ImageField(help_text='image size 100 by 100', upload_to='subectimages')),
                ('courseName', models.FileField(upload_to='')),
                ('coursePrice', models.PositiveIntegerField(help_text='Enter price in dollars')),
                ('courseDuration', models.DurationField(default=datetime.timedelta(seconds=19200))),
                ('courseSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='home.subjects')),
            ],
        ),
    ]
