# Generated by Django 4.2.13 on 2024-07-01 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_course_coursename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Subjects', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='course',
            name='courseDuration',
            field=models.DurationField(default=datetime.timedelta(seconds=19200), verbose_name='Course Duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseImage',
            field=models.ImageField(help_text='image size 100 by 100', upload_to='subectimages', verbose_name='Course Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(max_length=100, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursePrice',
            field=models.PositiveIntegerField(help_text='Enter price in dollars', verbose_name='Course Price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='home.subjects', verbose_name='Course Subject'),
        ),
    ]
