# Generated by Django 4.2.13 on 2024-07-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_code',
            field=models.PositiveIntegerField(default=174111),
        ),
    ]
