# Generated by Django 4.2.13 on 2024-07-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_customuser_activate_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
